# -*- coding: utf-8 -*-
"""matplotlib-learn-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQCWtb1GrVhyE1bJwC81HwDAcwabCJfp
"""

from IPython.display import YouTubeVideo
print(' *** Copyright *** Source Code dibawah hasil dari playlist Indonesia Belajar')
print(' yang sedikit saya modifikasi')
YouTubeVideo('2Mz5i8ehk5A')

"""**Belajar Matplotlib**

Modul:
- pip install matplotlib
- pip install numpy

pyplot adalah modul utama untuk melakukan ploting data

"""

import matplotlib.pyplot as plt
import numpy as np

"""- x = itu yang  datar 
- y = itu yang keatas untuk ketinggian

Figure dan akses dibuat secara otomatis saat subsplot dipanggil jadi siapkan variablenya

- ax itu buat nyimpan plot untuk dipanggil 
- fig = figur

"""

#sample data
x=[1,2,3,4]
y=[1,4,2,3]
x1=[1,2,3,4]
y1=[2,3,5,2]

#membuat figur dengan nama axes
fig, ax = plt.subplots()
#melaukan ploting
ax.plot(x,y)
ax.plot(x1,y1)

#cara sederhana dari yang diatas
plt.plot(x,y)
plt.plot(x1,y1)

#figure itu container nya berisi banyak axes
#figure dibawah belum memiliki axes
fig=plt.figure()

#figure ditambahkan axes
fig.ax=plt.subplots()

# (Baris, kolom)
fig.axs=plt.subplots(2,4) #menampilkan figure dengan 2x4 grid axes

"""Ada 2 Cara visualisasi dengan matplotlib
- Object Oriented Style
- pylot Style

**1. Object Oriented Style**

Membuat figure serta axes, dan memanggil method dari keduanya
"""

# Numpy linspace untuk melakukan generate terhadap sejumlah deret bilangan
# np.linspace( Nilai awal , Nilai Akhir , Jumlah data point yang ingin dibuat)
x = np.linspace(0, 2, 100)
# x = np.linspace(1,10,100)
print(x)

fig,ax=plt.subplots()

# sebenarnya isi dari method plot tetap x, y hanya saja datanya di generate menggunakan linspace jadi yang dipanggil x ,x sama aja kok
ax.plot(x, x, label='Linear') # ini linearnya
ax.plot(x, x**2, label="Quadratic") # dipangkatkan 2
ax.plot(x, x**3, label="Cubic") # dipangkatkan 3
#label sudut x dan sudut y
ax.set_xlabel('X axis')
ax.set_ylabel('Y axis')
#ini buat judul diatasnya
ax.set_title('Plotting Sederhana')
#nampilin kotak kecil buat label
ax.legend()

"""**2. Pyplot Style**

Dimana kita akan mengandalkat Pyplot untuk membuat dan mengelola figures dan axes, serta menggunakan fungsi pyplot untuk melakukan plotting

"""

#tidak perlu membuat figure dan axes fig,ax=subplots() karena dibuatkan pyplot secara otomatis

#generate data set
x=np.linspace(0,2,100)

plt.plot(x,x,label='linear')
plt.plot(x,x**2,label='kuadrat')
plt.plot(x,x**3,label='kubik')

#tidak pake set_xlabel langsung xlabel saja kalo pyplot
plt.xlabel('Sumbu X')
plt.ylabel('Sumbu Y')
plt.title('Plotting Pyplot Style')
plt.legend()

"""**Experiment**"""

x=np.linspace(0,1,100)


for i in range(2,6):
  plt.plot(x**i,x*i)
  plt.plot(x*i,x**i)
  plt.plot(x*i,x)
  plt.plot(x,x*i)
plt.plot(x*5,x*5) #menuju tak terbatas dan melampauinya plus ultra

plt.title('entah apa jadinya')
plt.xlabel('sumbu X')
plt.ylabel('sumbu Y')

type(x)

a=[1,1,3,3,1]
b=[1,2,2,1,1]
a1=[3,1]
b1=[1.5,1.5]
plt.plot(a,b)
plt.plot(a1,b1)
for i in range(1,4):
  for j in range(1,3):
    plt.scatter(i,j)
    plt.scatter(i-0.1,j)
plt.title('ngadi ngadi')

fig,ax=plt.subplots()
x=np.linspace(0,1,100)
for i in range(1,10):
  # ax.plot(x,x**i)
  ax.plot(x**i,x)
for i in range(2,10):
  ax.scatter(x,x**i)

plt.plot([1,3,4,5])

