# -*- coding: utf-8 -*-
"""matplotlib-learn-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lpRPnYOapf5zOwfMUBg7E71Iq_9TO-FO
"""

from IPython.display import YouTubeVideo
print(' *** Copyright *** Source Code dibawah hasil dari playlist Indonesia Belajar')
print(' yang sedikit saya modifikasi')
YouTubeVideo('l6BzdTkZNRY')

import matplotlib
import matplotlib.pyplot as plt
import numpy as np

"""Mengenal pyplot API

"""

#Cek version
print(matplotlib.__version__)
print(np.__version__)

"""plot(sumbu x, sumbu y, warna(namaWarna,tipe))

tipe - : Garis , tipe o : titik , tipe * : *

"""

plt.plot([1,2,3,4],[1,4,9,16],'ro')
#plt.axis( xmin,xmax,ymin,ymax)
plt.axis([0,6,0,20])
plt.show()

"""Numpy Arange ( nilai floating awal, nilai floating max, interval )"""

t=np.arange(0.,5.,0.2)
t

plt.plot(t,t,'r--') 
plt.plot(t,t**2,'bs') # s = kotak
plt.plot(t,t**3,'g^') # ^ = segitiga
plt.show()

plt.plot(t,t,'r--',t,t**2,'bs',t,t**3,'g^')
plt.title('multi plot')
plt.show()

"""- **np.arange(jumlah)** panggil 50 bilangan
- **np.random.randint(value awal, value akhir, jumlah)** acak bilangan dalam rentang value awal sampai akhir sebanyak jumlah
- **np.random.randn(jumlah)** acak sejumlah 50 saja
"""

data={
    'a':np.arange(50),
    'b':np.random.randint(0,50,50),
    'c':np.random.randn(50)
}

data

data['d'] = data['a']+10*np.random.randn(50)
data['c'] = np.abs(data['d'])*100
data

plt.scatter('a','d',data=data)
plt.xlabel('X axis')
plt.ylabel('Y axis')
plt.title("Ok")
plt.show()

"""**c** itu color atau warna, **s** itu sizenya atau ukuran

"""

plt.scatter('a','d',c='b',s='c',data=data)
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.show()